### ISSUE TITLE
var renderer: THREE.WebGLRenderer;

### ISSUE THREAD

**Issue by eladg** [PerthuisQuentin/desktop-3d-app-boilerplate#1]
Hello @PerthuisQuentin, 

Was trying to use this boilerplate today and found this little glitch in the template:

```javascript
import * as THREE from 'three';

import { scene, camera, update } from './content';

var renderer: THREE.WebGLRenderer;

init();
animate();
....
```
As far as I understand (my first days with electron) the `:` should be `=`

Thanks for the template, it actually really helps!

**Comment by PerthuisQuentin** [comment]
Hi !

Thanks, I will fix it now :)

Happy that it can help people !

**Comment by PerthuisQuentin** [comment]
I had forgotten that this boilerplate use Typescript.

The `:` is normal, it's to tell the type of `renderer`

So, I just update dependencies :)
